{
 "title": "LoRaWAN example",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "window", "label": "Rolling window size:" },
   { "name": "every", "label": "Sample frequency:" },
   {
    "name": "devices",
    "label": "Show devices:",
    "query": {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> keep(columns: [\"dev_eui\"]) |> group() |> distinct(column: \"dev_eui\")"
    }
   },
   {
    "name": "timeRangeStartMinusWindow",
    "query": {
     "query": "import \"date\" import \"array\" array.from(rows: [{_value: string(v: date.sub(d: ${window}, from: v.timeRangeStart))}])"
    }
   }
  ]
 },
 "panels": [
  { "title": "Signal quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received Signal Strength Indicator (RSSI)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> keep(columns: [\"_time\", \"dev_eui\", \"_value\"])\r\n  |> group(columns: [\"_time\",\"dev_eui\"]) |> max() |> group(columns: [\"dev_eui\"])\r\n"
    }
   ]
  },
  {
   "title": "Signal to Noise Ratio (SNR)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.snr\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"_time\",\"dev_eui\"]) |> max() |> group(columns: [\"dev_eui\"])\r\n  |> keep(columns: [\"_time\", \"dev_eui\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "RSSI (timed moving average)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"_time\",\"dev_eui\"]) |> max() |> group(columns: [\"dev_eui\"])\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "SNR (timed moving average)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.snr\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"_time\",\"dev_eui\"]) |> max() |> group(columns: [\"dev_eui\"])\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: mean) "
    }
   ]
  },
  {
   "title": "Spreading Factor (SF)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> map(fn: (r) => ({r with _value: int(v: r[\"tx_info.modulation.lora.spreading_factor\"])}))\r\n  |> group(columns: [\"dev_eui\"])\r\n  |> keep(columns: [\"_time\", \"dev_eui\", \"_value\"])\r\n"
    }
   ]
  },
  { "title": "Link reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Global Packet Delivery Ratio (PDR)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "packets = from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"dev_eui\", \"phy_payload.payload.fhdr.devaddr\"]) \r\n  |> unique(column: \"phy_payload.payload.fhdr.f_cnt\") \r\n  |> group()\r\n\r\nrecv = packets \r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: count)\r\n  |> group(columns: [\"_start\", \"_stop\", \"_time\"]) |> max() |> group()\r\n\r\nsent = packets\r\n  |> map(fn: (r) => ({r with _value: int(v: r[\"phy_payload.payload.fhdr.f_cnt\"])}))\r\n  |> group(columns: [\"dev_eui\"]) |> sort(columns: [\"_time\"]) \r\n  |> difference(nonNegative: true, keepFirst: true) |> fill(value: 1)\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: sum)\r\n  |> group(columns: [\"_start\", \"_stop\", \"_time\", \"dev_eui\"]) |> max()\r\n  |> group(columns: [\"_start\", \"_stop\", \"_time\"]) |> sum() |> group()\r\n\r\njoin(tables: {sent: sent, recv: recv}, on: [\"_start\", \"_stop\", \"_time\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value_recv) / float(v: r._value_sent)}))\r\n  |> drop(columns: [\"_value_recv\", \"_value_sent\"])\r\n  |> group(columns: [\"_start\", \"_stop\"])\r\n"
    }
   ]
  },
  {
   "title": "Packet Delivery Ratio (PDR)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "packets = from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"dev_eui\", \"phy_payload.payload.fhdr.devaddr\"]) \r\n  |> unique(column: \"phy_payload.payload.fhdr.f_cnt\") \r\n  |> group(columns: [\"dev_eui\"])\r\n\r\nrecv = packets \r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: count)\r\n  |> group(columns: [\"_start\", \"_stop\", \"_time\", \"dev_eui\"]) |> max() |> group(columns: [\"dev_eui\"])\r\n\r\nsent = packets\r\n  |> map(fn: (r) => ({r with _value: int(v: r[\"phy_payload.payload.fhdr.f_cnt\"])}))\r\n  |> sort(columns: [\"_time\"]) |> difference(nonNegative: true, keepFirst: true) |> fill(value: 1)\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: sum)\r\n  |> group(columns: [\"_start\", \"_stop\", \"_time\", \"dev_eui\"]) |> max()\r\n  |> group(columns: [\"dev_eui\"])\r\n\r\njoin(tables: {sent: sent, recv: recv}, on: [\"_start\", \"_stop\", \"_time\", \"dev_eui\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value_recv) / float(v: r._value_sent)}))\r\n  |> drop(columns: [\"_value_recv\", \"_value_sent\"])\r\n  |> group(columns: [\"_start\", \"_stop\", \"dev_eui\"])"
    }
   ]
  },
  { "title": "Radio utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Hourly # of unique uplink packets",
   "type": "timeseries",
   "description": "Results are deduplicated",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"chirpstack\")\r\n  |> range(start: date.sub(d: 1h, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"dev_eui\", \"phy_payload.payload.fhdr.devaddr\"])\r\n  |> unique(column: \"phy_payload.payload.fhdr.f_cnt\")\r\n  |> group(columns: [\"dev_eui\"])\r\n  |> aggregateWindow(every: 1h, fn: count)\r\n"
    }
   ]
  },
  {
   "title": "% RX by sender",
   "type": "timeseries",
   "description": "Results are deduplicated",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"dev_eui\", \"phy_payload.payload.fhdr.devaddr\"]) \r\n  |> unique(column: \"phy_payload.payload.fhdr.f_cnt\") \r\n  |> group(columns: [\"dev_eui\"])\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: count)"
    }
   ]
  },
  {
   "title": "% RX by Spreading Factor (SF)",
   "type": "timeseries",
   "description": "Results are deduplicated",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"dev_eui\", \"phy_payload.payload.fhdr.devaddr\"])\r\n  |> unique(column: \"phy_payload.payload.fhdr.f_cnt\")\r\n  |> group(columns: [\"tx_info.modulation.lora.spreading_factor\"])\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: count)\r\n"
    }
   ]
  },
  {
   "title": "% RX by carrier frequency [Hz]",
   "type": "timeseries",
   "description": "Results are deduplicated",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"dev_eui\", \"phy_payload.payload.fhdr.devaddr\"])\r\n  |> unique(column: \"phy_payload.payload.fhdr.f_cnt\")\r\n  |> group(columns: [\"tx_info.frequency\"])\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: count)\r\n"
    }
   ]
  },
  {
   "title": "Avg # duplicated Rx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"chirpstack\")\r\n  |> range(start: ${timeRangeStartMinusWindow}, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_uplink_frame_log\" and r._field == \"rx_info.rssi\")\r\n  |> filter(fn: (r) => contains(set: [${devices:doublequote}], value: r.dev_eui))\r\n  |> group(columns: [\"_time\", \"dev_eui\"]) |> count() |> group(columns: [\"dev_eui\"])\r\n  |> aggregateWindow(every: ${every}, period: ${window}, fn: mean)\r\n"
    }
   ]
  }
 ]
}